name: client

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./so-go-client
        
      - name: Build
        run: npm run build
        working-directory: ./so-go-client
        
      - name: SHOW AWS CLI VERSION
        run: |
          aws --version
          which aws
          
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build s3://so-go \
            --delete
        working-directory: ./so-go-client
